
GET http://localhost:3000/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjYsImlhdCI6MTY1MzU5MzY0NiwiZXhwIjoxNjUzNTk3MjQ2fQ.TtN4_Q_Z-VbYFhSHGlluJ82w7D5q0xiDrBYgIwGCMLs

###----------------------------/register

POST http://localhost:3000/api/register
Content-Type: application/json

 {
    "full_name": "marius1",
    "email": "marius1@xxx.lt",
    "password": "123456"
    
  }

###------------------------------login'

POST http://localhost:3000/api/login
Content-Type: application/json

 {
    "full_name": "marius1",
    "email": "marius1@xxx.lt",
    "password": "123456"
    
  }

###-----------------POST accounts

POST http://localhost:3000/api/accounts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjYsImlhdCI6MTY1MzUwNjc5NywiZXhwIjoxNjUzNTEwMzk3fQ.AUlZBKKNqtqZjw98oSFhQMHlbvv_7xZ5c67Hu-7IC6Q

 {
    "group_id": "4",
    "user_id": "2"
        
  }

###---------------------get aCCOUNT
GET http://localhost:3000/api/accounts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjYsImlhdCI6MTY1MzU5ODUzMywiZXhwIjoxNjUzNjAyMTMzfQ.g6G00yP0yYONUSMjsc3qCiwV6dGlWDKeq7RnhKety74

###-------------------------get /bills/:group_id
GET http://localhost:3000/api/bills/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjYsImlhdCI6MTY1MzU0NTg5MSwiZXhwIjoxNjUzNTQ5NDkxfQ.qBmbeMDcLwnWm5K3HhBAXXWg0Yah-DU59URycj6QULQ

####---------------------POST bill

POST http://localhost:3000/api/bills?group_id=2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjYsImlhdCI6MTY1MzU0NTg5MSwiZXhwIjoxNjUzNTQ5NDkxfQ.qBmbeMDcLwnWm5K3HhBAXXWg0Yah-DU59URycj6QULQ

 {
    "group_id": 1,
    "amount": 25,
    "description": "Uz nakvyne"
        
  }