
GET http://localhost:3000/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjYsImlhdCI6MTY1MzUwNjc5NywiZXhwIjoxNjUzNTEwMzk3fQ.AUlZBKKNqtqZjw98oSFhQMHlbvv_7xZ5c67Hu-7IC6Q

###----------------------------/register

POST http://localhost:3000/api/register
Content-Type: application/json

 {
    "full_name": "marius1",
    "email": "marius1@xxx.lt",
    "password": "123456"
    
  }

###------------------------------login'

POST http://localhost:3000/api/login
Content-Type: application/json

 {
    "full_name": "marius1",
    "email": "marius1@xxx.lt",
    "password": "123456"
    
  }

###-----------------POST accounts

POST http://localhost:3000/api/accounts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjYsImlhdCI6MTY1MzUwNjc5NywiZXhwIjoxNjUzNTEwMzk3fQ.AUlZBKKNqtqZjw98oSFhQMHlbvv_7xZ5c67Hu-7IC6Q

 {
    "group_id": "4",
    "user_id": "2"
        
  }

###---------------------get aCCOUNT
GET http://localhost:3000/api/accounts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjYsImlhdCI6MTY1MzUwOTc4NSwiZXhwIjoxNjUzNTEzMzg1fQ.3LI9mwr_-VVyOOzV77-dBmoqJQH9cJrsbYyZgyZYKDY